steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'discord_bot', '--trigger-http', '--runtime', 'python37', '--entry-point', 'discord_bot', '--allow-unauthenticated']
  dir: './'

  # project number 